<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,ConfName?,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Doc*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC|BPTWrapperTest|Flow|Group) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT ConfName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step*,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*,Summary,ActionMaintenanceSummary*,NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?,ExtendedInfo? )>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED UserNote CDATA #IMPLIED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT ExtendedInfo ( StepData ) >

<!ATTLIST ExtendedInfo StepType CDATA #REQUIRED>
<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="India Standard Time">
<General productName="QuickTest Professional" productVer="11.00" os="Windows 7" host="CNVN-LAP1"><DocLocation><![CDATA[D:\CRAFT - EBS Master-06022014\CRAFT - EBS Master-06022014\Driver Script]]></DocLocation></General>
<Doc rID="T1"   productName= "QuickTest Professional"  >
<DName><![CDATA[Driver Script]]></DName>
<Res><![CDATA[Res7]]></Res>
<DT rID="T2">
<NodeArgs eType="Table" icon="2" nRep="4" filter="False" >
<Disp><![CDATA[Run-Time Data Table]]></Disp>
<BtmPane vType="Table">
<Path><![CDATA[Default.xls]]></Path>
</BtmPane>
</NodeArgs>
</DT>
<Action rID="T3">
<AName><![CDATA[Action1]]></AName>
<Step rID="T4">
<Obj ><![CDATA[Start]]></Obj>
<Details ><![CDATA[Iteration1 started]]></Details>
<Time><![CDATA[4/3/2014 - 14:12:36]]></Time>
<TimeTick>1396514556</TimeTick>
<NodeArgs eType="User" icon="4" nRep="7" >
<Disp><![CDATA[Start]]></Disp>
</NodeArgs>
</Step>
<Step rID="T5">
<Obj ><![CDATA[Start Component]]></Obj>
<Details ><![CDATA[Invoking Business component: Login]]></Details>
<Time><![CDATA[4/3/2014 - 14:12:37]]></Time>
<TimeTick>1396514557</TimeTick>
<NodeArgs eType="User" icon="4" nRep="8" >
<Disp><![CDATA[Start Component]]></Disp>
</NodeArgs>
</Step>
<Step rID="T6">
<Obj plainTxt="False" ><![CDATA[SystemUtil]]></Obj>
<Details plainTxt="False" ><![CDATA[SystemUtil]]></Details>
<Time><![CDATA[4/3/2014 - 14:12:37]]></Time>
<TimeTick>1396514557</TimeTick>
<Step rID="T7">
<Obj plainTxt="False" ><![CDATA[Run "iexplore",3]]></Obj>
<Details plainTxt="False" ><![CDATA[Run "iexplore",3]]></Details>
<Time><![CDATA[4/3/2014 - 14:12:37]]></Time>
<TimeTick>1396514557</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="12" status="Passed" >
<Disp><![CDATA[Run "iexplore",3]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="5" nRep="11" status="Passed" >
<Disp><![CDATA[SystemUtil]]></Disp>
</NodeArgs>
</Step>
<Step rID="T8">
<Obj plainTxt="False" ><![CDATA[Login]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[4/3/2014 - 14:12:37]]></Time>
<TimeTick>1396514557</TimeTick>
<Step rID="T9">
<Obj plainTxt="False" ><![CDATA[Login]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[4/3/2014 - 14:12:37]]></Time>
<TimeTick>1396514557</TimeTick>
<Step rID="T10">
<Obj plainTxt="False" ><![CDATA[usernameField.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[4/3/2014 - 14:12:37]]></Time>
<TimeTick>1396514557</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="16" >
<Disp><![CDATA[usernameField.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T11">
<Obj plainTxt="False" ><![CDATA[usernameField.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["mall1068"]]></Details>
<Time><![CDATA[4/3/2014 - 14:12:37]]></Time>
<TimeTick>1396514557</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="19" >
<Disp><![CDATA[usernameField.Set]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="15" >
<Disp><![CDATA[Login]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="14" >
<Disp><![CDATA[Login]]></Disp>
</NodeArgs>
</Step>
<Step rID="T12">
<Obj ><![CDATA[Login ]]></Obj>
<Details ><![CDATA[User name mall1068 is entered ]]></Details>
<Time><![CDATA[4/3/2014 - 14:12:38]]></Time>
<TimeTick>1396514558</TimeTick>
<NodeArgs eType="User" icon="4" nRep="20" >
<Disp><![CDATA[Login ]]></Disp>
</NodeArgs>
</Step>
<Step rID="T13">
<Obj plainTxt="False" ><![CDATA[Login]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[4/3/2014 - 14:12:38]]></Time>
<TimeTick>1396514558</TimeTick>
<Step rID="T14">
<Obj plainTxt="False" ><![CDATA[Login]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[4/3/2014 - 14:12:38]]></Time>
<TimeTick>1396514558</TimeTick>
<Step rID="T15">
<Obj plainTxt="False" ><![CDATA[passwordField.SetSecure]]></Obj>
<Details plainTxt="False" ><![CDATA["racker5"]]></Details>
<Time><![CDATA[4/3/2014 - 14:12:38]]></Time>
<TimeTick>1396514558</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="25" >
<Disp><![CDATA[passwordField.SetSecure]]></Disp>
</NodeArgs>
</Step>
<Step rID="T16">
<Obj plainTxt="False" ><![CDATA[Login.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[4/3/2014 - 14:12:38]]></Time>
<TimeTick>1396514558</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="28" >
<Disp><![CDATA[Login.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="24" >
<Disp><![CDATA[Login]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="23" >
<Disp><![CDATA[Login]]></Disp>
</NodeArgs>
</Step>
<Step rID="T17">
<Obj ><![CDATA[Login ]]></Obj>
<Details ><![CDATA[Login button is clicked]]></Details>
<Time><![CDATA[4/3/2014 - 14:12:38]]></Time>
<TimeTick>1396514558</TimeTick>
<NodeArgs eType="User" icon="4" nRep="29" >
<Disp><![CDATA[Login ]]></Disp>
</NodeArgs>
</Step>
<Step rID="T18">
<Obj plainTxt="False" ><![CDATA[Login]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[4/3/2014 - 14:12:40]]></Time>
<TimeTick>1396514560</TimeTick>
<Step rID="T19">
<Obj plainTxt="False" ><![CDATA[Oracle Applications Home_2]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[4/3/2014 - 14:12:40]]></Time>
<TimeTick>1396514560</TimeTick>
<Step rID="T20">
<Obj plainTxt="False" ><![CDATA[Logout.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[4/3/2014 - 14:12:40]]></Time>
<TimeTick>1396514560</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="33" >
<Disp><![CDATA[Logout.Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="32" >
<Disp><![CDATA[Oracle Applications Home_2]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="31" >
<Disp><![CDATA[Login]]></Disp>
</NodeArgs>
</Step>
<Step rID="T21">
<Obj ><![CDATA[Login ]]></Obj>
<Details ><![CDATA[Successfully logined]]></Details>
<Time><![CDATA[4/3/2014 - 14:12:40]]></Time>
<TimeTick>1396514560</TimeTick>
<NodeArgs eType="User" icon="4" nRep="34" status="Passed" >
<Disp><![CDATA[Login ]]></Disp>
</NodeArgs>
</Step>
<Step rID="T22">
<Obj ><![CDATA[Login ]]></Obj>
<Details ><![CDATA[Successfully logined]]></Details>
<Time><![CDATA[4/3/2014 - 14:12:40]]></Time>
<TimeTick>1396514560</TimeTick>
<NodeArgs eType="User" icon="4" nRep="35" >
<Disp><![CDATA[Login ]]></Disp>
</NodeArgs>
</Step>
<Step rID="T23">
<Obj ><![CDATA[End Component]]></Obj>
<Details ><![CDATA[Exiting Business component: Login]]></Details>
<Time><![CDATA[4/3/2014 - 14:12:40]]></Time>
<TimeTick>1396514560</TimeTick>
<NodeArgs eType="User" icon="4" nRep="36" >
<Disp><![CDATA[End Component]]></Disp>
</NodeArgs>
</Step>
<Step rID="T24">
<Obj ><![CDATA[Start Component]]></Obj>
<Details ><![CDATA[Invoking Business component: Naviagte_Doc_Seq]]></Details>
<Time><![CDATA[4/3/2014 - 14:12:41]]></Time>
<TimeTick>1396514561</TimeTick>
<NodeArgs eType="User" icon="4" nRep="37" >
<Disp><![CDATA[Start Component]]></Disp>
</NodeArgs>
</Step>
<Step rID="T25">
<Obj plainTxt="False" ><![CDATA[[ System Administrator ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[4/3/2014 - 14:12:42]]></Time>
<TimeTick>1396514562</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="42" >
<Disp><![CDATA[[ System Administrator ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T26">
<Obj plainTxt="False" ><![CDATA[[ System Administrator ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[4/3/2014 - 14:12:45]]></Time>
<TimeTick>1396514565</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="45" >
<Disp><![CDATA[[ System Administrator ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T27">
<Obj ><![CDATA[Link Clicked]]></Obj>
<Details ><![CDATA[The link ' System Administrator' is available and clicked]]></Details>
<Time><![CDATA[4/3/2014 - 14:12:45]]></Time>
<TimeTick>1396514565</TimeTick>
<NodeArgs eType="User" icon="4" nRep="46" >
<Disp><![CDATA[Link Clicked]]></Disp>
</NodeArgs>
</Step>
<Step rID="T28">
<Obj plainTxt="False" ><![CDATA[Oracle Applications Home Page]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[4/3/2014 - 14:12:49]]></Time>
<TimeTick>1396514569</TimeTick>
<Step rID="T29">
<Obj plainTxt="False" ><![CDATA[Oracle Applications Home_6]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[4/3/2014 - 14:12:49]]></Time>
<TimeTick>1396514569</TimeTick>
<Step rID="T30">
<Obj plainTxt="False" ><![CDATA[Assign.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[4/3/2014 - 14:12:49]]></Time>
<TimeTick>1396514569</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="52" >
<Disp><![CDATA[Assign.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T31">
<Obj plainTxt="False" ><![CDATA[Stop Run]]></Obj>
<Details plainTxt="False" ><![CDATA[Run stopped by user.]]></Details>
<Time><![CDATA[4/3/2014 - 14:12:53]]></Time>
<TimeTick>1396514573</TimeTick>
<NodeArgs eType="General" icon="11" nRep="53" >
<Disp><![CDATA[Stop Run]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="51" >
<Disp><![CDATA[Oracle Applications Home_6]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="50" >
<Disp><![CDATA[Oracle Applications Home Page]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="4/3/2014 - 14:12:35" eTime="4/3/2014 - 14:12:53" passed="2" failed="0" warnings="0" ><Param ><ParamName><![CDATA[CurrentScenario]]></ParamName><ParamVal><![CDATA[Sys_Admin]]></ParamVal>
</Param>
<Param ><ParamName><![CDATA[CurrentTestCase]]></ParamName><ParamVal><![CDATA[TC2]]></ParamVal>
</Param>
<Param ><ParamName><![CDATA[TestCaseDescription]]></ParamName><ParamVal><![CDATA[Assign Document Seq]]></ParamVal>
</Param>
<Param ><ParamName><![CDATA[TimeStamp]]></ParamName><ParamVal><![CDATA[Run_1-11-2013_1-54-09 PM]]></ParamVal>
</Param>
<Param ><ParamName><![CDATA[IterationMode]]></ParamName><ParamVal><![CDATA[oneIteration]]></ParamVal>
</Param>
<Param ><ParamName><![CDATA[StartIteration]]></ParamName><ParamVal><![CDATA[1]]></ParamVal>
</Param>
<Param ><ParamName><![CDATA[EndIteration]]></ParamName><ParamVal><![CDATA[1]]></ParamVal>
</Param>
</Summary>
<NodeArgs eType="StartAction" icon="3" nRep="6" status="Passed" >
<Disp><![CDATA[Action1 Summary]]></Disp>
</NodeArgs>
</Action>
<Step rID="T32">
<Obj plainTxt="False" ><![CDATA[Stop Run]]></Obj>
<Details plainTxt="False" ><![CDATA[Run stopped by user.]]></Details>
<Time><![CDATA[4/3/2014 - 14:12:53]]></Time>
<TimeTick>1396514573</TimeTick>
<NodeArgs eType="General" icon="12" nRep="55" >
<Disp><![CDATA[Stop Run]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="4/3/2014 - 14:12:33" eTime="4/3/2014 - 14:12:53" passed="2" failed="0" warnings="0" stopped="True" ><Param ><ParamName><![CDATA[CurrentScenario]]></ParamName><ParamVal><![CDATA[Sys_Admin]]></ParamVal>
</Param>
<Param ><ParamName><![CDATA[CurrentTestCase]]></ParamName><ParamVal><![CDATA[TC2]]></ParamVal>
</Param>
<Param ><ParamName><![CDATA[TestCaseDescription]]></ParamName><ParamVal><![CDATA[Assign Document Seq]]></ParamVal>
</Param>
<Param ><ParamName><![CDATA[TimeStamp]]></ParamName><ParamVal><![CDATA[Run_1-11-2013_1-54-09 PM]]></ParamVal>
</Param>
<Param ><ParamName><![CDATA[IterationMode]]></ParamName><ParamVal><![CDATA[oneIteration]]></ParamVal>
</Param>
<Param ><ParamName><![CDATA[StartIteration]]></ParamName><ParamVal><![CDATA[1]]></ParamVal>
</Param>
<Param ><ParamName><![CDATA[EndIteration]]></ParamName><ParamVal><![CDATA[1]]></ParamVal>
</Param>
</Summary>
<NodeArgs eType="StartTest" icon="1" nRep="3" status="Passed" >
<Disp><![CDATA[Test Driver Script Summary]]></Disp>
</NodeArgs>
</Doc>
</Report>