<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,ConfName?,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Doc*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC|BPTWrapperTest|Flow|Group) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT ConfName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step*,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*,Summary,ActionMaintenanceSummary*,NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?,ExtendedInfo? )>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED UserNote CDATA #IMPLIED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT ExtendedInfo ( StepData ) >

<!ATTLIST ExtendedInfo StepType CDATA #REQUIRED>
<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="India Standard Time">
<General productName="QuickTest Professional" productVer="11.00" os="Windows 7" host="CNVN-LAP1"><DocLocation><![CDATA[C:\Users\Nagarjuna\Desktop\CRAFT - EBS Master-Data-New-21-11-2014\Driver Script]]></DocLocation></General>
<Doc rID="T1"   productName= "QuickTest Professional"  >
<DName><![CDATA[Driver Script]]></DName>
<Res><![CDATA[TC62]]></Res>
<DT rID="T2">
<NodeArgs eType="Table" icon="2" nRep="4" filter="False" >
<Disp><![CDATA[Run-Time Data Table]]></Disp>
<BtmPane vType="Table">
<Path><![CDATA[Default.xls]]></Path>
</BtmPane>
</NodeArgs>
</DT>
<Action rID="T3">
<AName><![CDATA[Action1]]></AName>
<Step rID="T4">
<Obj ><![CDATA[Start]]></Obj>
<Details ><![CDATA[Iteration1 started]]></Details>
<Time><![CDATA[12/23/2014 - 7:17:23]]></Time>
<TimeTick>1419299243</TimeTick>
<NodeArgs eType="User" icon="4" nRep="7" >
<Disp><![CDATA[Start]]></Disp>
</NodeArgs>
</Step>
<Step rID="T5">
<Obj ><![CDATA[Start Component]]></Obj>
<Details ><![CDATA[Invoking Business component: Login]]></Details>
<Time><![CDATA[12/23/2014 - 7:17:24]]></Time>
<TimeTick>1419299244</TimeTick>
<NodeArgs eType="User" icon="4" nRep="8" >
<Disp><![CDATA[Start Component]]></Disp>
</NodeArgs>
</Step>
<Step rID="T6">
<Obj plainTxt="False" ><![CDATA[SystemUtil]]></Obj>
<Details plainTxt="False" ><![CDATA[SystemUtil]]></Details>
<Time><![CDATA[12/23/2014 - 7:17:25]]></Time>
<TimeTick>1419299245</TimeTick>
<Step rID="T7">
<Obj plainTxt="False" ><![CDATA[Run "iexplore",3]]></Obj>
<Details plainTxt="False" ><![CDATA[Run "iexplore",3]]></Details>
<Time><![CDATA[12/23/2014 - 7:17:25]]></Time>
<TimeTick>1419299245</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="12" status="Passed" >
<Disp><![CDATA[Run "iexplore",3]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="5" nRep="11" status="Passed" >
<Disp><![CDATA[SystemUtil]]></Disp>
</NodeArgs>
</Step>
<Step rID="T8">
<Obj plainTxt="False" ><![CDATA[Login]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[12/23/2014 - 7:17:31]]></Time>
<TimeTick>1419299251</TimeTick>
<Step rID="T9">
<Obj plainTxt="False" ><![CDATA[Login]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[12/23/2014 - 7:17:31]]></Time>
<TimeTick>1419299251</TimeTick>
<Step rID="T10">
<Obj plainTxt="False" ><![CDATA[usernameField.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[12/23/2014 - 7:17:31]]></Time>
<TimeTick>1419299251</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="32" >
<Disp><![CDATA[usernameField.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T11">
<Obj plainTxt="False" ><![CDATA[usernameField.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["mura1425"]]></Details>
<Time><![CDATA[12/23/2014 - 7:17:31]]></Time>
<TimeTick>1419299251</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="35" >
<Disp><![CDATA[usernameField.Set]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="31" >
<Disp><![CDATA[Login]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="30" >
<Disp><![CDATA[Login]]></Disp>
</NodeArgs>
</Step>
<Step rID="T12">
<Obj ><![CDATA[Login ]]></Obj>
<Details ><![CDATA[User name mura1425 is entered ]]></Details>
<Time><![CDATA[12/23/2014 - 7:17:31]]></Time>
<TimeTick>1419299251</TimeTick>
<NodeArgs eType="User" icon="4" nRep="36" >
<Disp><![CDATA[Login ]]></Disp>
</NodeArgs>
</Step>
<Step rID="T13">
<Obj plainTxt="False" ><![CDATA[Login]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[12/23/2014 - 7:17:31]]></Time>
<TimeTick>1419299251</TimeTick>
<Step rID="T14">
<Obj plainTxt="False" ><![CDATA[Login]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[12/23/2014 - 7:17:31]]></Time>
<TimeTick>1419299251</TimeTick>
<Step rID="T15">
<Obj plainTxt="False" ><![CDATA[passwordField.SetSecure]]></Obj>
<Details plainTxt="False" ><![CDATA["racker5"]]></Details>
<Time><![CDATA[12/23/2014 - 7:17:31]]></Time>
<TimeTick>1419299251</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="41" >
<Disp><![CDATA[passwordField.SetSecure]]></Disp>
</NodeArgs>
</Step>
<Step rID="T16">
<Obj plainTxt="False" ><![CDATA[Login.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[12/23/2014 - 7:17:31]]></Time>
<TimeTick>1419299251</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="44" >
<Disp><![CDATA[Login.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="40" >
<Disp><![CDATA[Login]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="39" >
<Disp><![CDATA[Login]]></Disp>
</NodeArgs>
</Step>
<Step rID="T17">
<Obj ><![CDATA[Login ]]></Obj>
<Details ><![CDATA[Login button is clicked]]></Details>
<Time><![CDATA[12/23/2014 - 7:17:31]]></Time>
<TimeTick>1419299251</TimeTick>
<NodeArgs eType="User" icon="4" nRep="45" >
<Disp><![CDATA[Login ]]></Disp>
</NodeArgs>
</Step>
<Step rID="T18">
<Obj plainTxt="False" ><![CDATA[Login]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[12/23/2014 - 7:17:33]]></Time>
<TimeTick>1419299253</TimeTick>
<Step rID="T19">
<Obj plainTxt="False" ><![CDATA[Oracle Applications Home_2]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[12/23/2014 - 7:17:33]]></Time>
<TimeTick>1419299253</TimeTick>
<Step rID="T20">
<Obj plainTxt="False" ><![CDATA[Logout.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[12/23/2014 - 7:17:33]]></Time>
<TimeTick>1419299253</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="49" >
<Disp><![CDATA[Logout.Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="48" >
<Disp><![CDATA[Oracle Applications Home_2]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="47" >
<Disp><![CDATA[Login]]></Disp>
</NodeArgs>
</Step>
<Step rID="T21">
<Obj ><![CDATA[Login ]]></Obj>
<Details ><![CDATA[Successfully logined]]></Details>
<Time><![CDATA[12/23/2014 - 7:17:33]]></Time>
<TimeTick>1419299253</TimeTick>
<NodeArgs eType="User" icon="4" nRep="50" status="Passed" >
<Disp><![CDATA[Login ]]></Disp>
</NodeArgs>
</Step>
<Step rID="T22">
<Obj ><![CDATA[Login ]]></Obj>
<Details ><![CDATA[Successfully logined]]></Details>
<Time><![CDATA[12/23/2014 - 7:17:33]]></Time>
<TimeTick>1419299253</TimeTick>
<NodeArgs eType="User" icon="4" nRep="51" >
<Disp><![CDATA[Login ]]></Disp>
</NodeArgs>
</Step>
<Step rID="T23">
<Obj ><![CDATA[End Component]]></Obj>
<Details ><![CDATA[Exiting Business component: Login]]></Details>
<Time><![CDATA[12/23/2014 - 7:17:33]]></Time>
<TimeTick>1419299253</TimeTick>
<NodeArgs eType="User" icon="4" nRep="52" >
<Disp><![CDATA[End Component]]></Disp>
</NodeArgs>
</Step>
<Step rID="T24">
<Obj ><![CDATA[Start Component]]></Obj>
<Details ><![CDATA[Invoking Business component: Transfer_IT_To_GL]]></Details>
<Time><![CDATA[12/23/2014 - 7:17:33]]></Time>
<TimeTick>1419299253</TimeTick>
<NodeArgs eType="User" icon="4" nRep="53" >
<Disp><![CDATA[Start Component]]></Disp>
</NodeArgs>
</Step>
<Step rID="T25">
<Obj plainTxt="False" ><![CDATA[[ RS MXN GL Manager ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[12/23/2014 - 7:17:33]]></Time>
<TimeTick>1419299253</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="55" >
<Disp><![CDATA[[ RS MXN GL Manager ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T26">
<Obj plainTxt="False" ><![CDATA[[ RS MXN GL Manager ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[12/23/2014 - 7:17:33]]></Time>
<TimeTick>1419299253</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="58" >
<Disp><![CDATA[[ RS MXN GL Manager ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T27">
<Obj ><![CDATA[Link Clicked]]></Obj>
<Details ><![CDATA[The link ' RS MXN GL Manager' is available and clicked]]></Details>
<Time><![CDATA[12/23/2014 - 7:17:33]]></Time>
<TimeTick>1419299253</TimeTick>
<NodeArgs eType="User" icon="4" nRep="59" >
<Disp><![CDATA[Link Clicked]]></Disp>
</NodeArgs>
</Step>
<Step rID="T28">
<Obj plainTxt="False" ><![CDATA[[ Enter ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[12/23/2014 - 7:17:39]]></Time>
<TimeTick>1419299259</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="61" >
<Disp><![CDATA[[ Enter ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T29">
<Obj plainTxt="False" ><![CDATA[[ Enter ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[12/23/2014 - 7:17:39]]></Time>
<TimeTick>1419299259</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="64" >
<Disp><![CDATA[[ Enter ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T30">
<Obj ><![CDATA[Link Clicked]]></Obj>
<Details ><![CDATA[The link ' Enter' is available and clicked]]></Details>
<Time><![CDATA[12/23/2014 - 7:17:39]]></Time>
<TimeTick>1419299259</TimeTick>
<NodeArgs eType="User" icon="4" nRep="65" >
<Disp><![CDATA[Link Clicked]]></Disp>
</NodeArgs>
</Step>
<Step rID="T31">
<Obj plainTxt="False" ><![CDATA[Find Journals]]></Obj>
<Details plainTxt="False" ><![CDATA[OracleFormWindow]]></Details>
<Time><![CDATA[12/23/2014 - 7:18:39]]></Time>
<TimeTick>1419299319</TimeTick>
<Step rID="T32">
<Obj plainTxt="False" ><![CDATA[Find Journals.CloseWindow]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[12/23/2014 - 7:18:39]]></Time>
<TimeTick>1419299319</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="68" >
<Disp><![CDATA[Find Journals.CloseWindow]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="11" nRep="67" >
<Disp><![CDATA[Find Journals]]></Disp>
</NodeArgs>
</Step>
<Step rID="T33">
<Obj plainTxt="False" ><![CDATA[Enter Journals]]></Obj>
<Details plainTxt="False" ><![CDATA[OracleFormWindow]]></Details>
<Time><![CDATA[12/23/2014 - 7:18:43]]></Time>
<TimeTick>1419299323</TimeTick>
<Step rID="T34">
<Obj plainTxt="False" ><![CDATA[Enter Journals.CloseWindow]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[12/23/2014 - 7:18:43]]></Time>
<TimeTick>1419299323</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="71" >
<Disp><![CDATA[Enter Journals.CloseWindow]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="11" nRep="70" >
<Disp><![CDATA[Enter Journals]]></Disp>
</NodeArgs>
</Step>
<Step rID="T35">
<Obj plainTxt="False" ><![CDATA[Navigator]]></Obj>
<Details plainTxt="False" ><![CDATA[OracleFormWindow]]></Details>
<Time><![CDATA[12/23/2014 - 7:18:48]]></Time>
<TimeTick>1419299328</TimeTick>
<Step rID="T36">
<Obj plainTxt="False" ><![CDATA[Navigator.SelectMenu]]></Obj>
<Details plainTxt="False" ><![CDATA["File-&gtSwitch Responsibility..."]]></Details>
<Time><![CDATA[12/23/2014 - 7:18:48]]></Time>
<TimeTick>1419299328</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="74" >
<Disp><![CDATA[Navigator.SelectMenu]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="11" nRep="73" >
<Disp><![CDATA[Navigator]]></Disp>
</NodeArgs>
</Step>
<Step rID="T37">
<Obj plainTxt="False" ><![CDATA[Responsibilities]]></Obj>
<Details plainTxt="False" ><![CDATA[OracleListOfValues]]></Details>
<Time><![CDATA[12/23/2014 - 7:18:52]]></Time>
<TimeTick>1419299332</TimeTick>
<Step rID="T38">
<Obj plainTxt="False" ><![CDATA[Responsibilities.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["RS ILS Intercompany User"]]></Details>
<Time><![CDATA[12/23/2014 - 7:18:52]]></Time>
<TimeTick>1419299332</TimeTick>
<NodeArgs eType="Replay" icon="12" nRep="77" >
<Disp><![CDATA[Responsibilities.Select]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="12" nRep="76" >
<Disp><![CDATA[Responsibilities]]></Disp>
</NodeArgs>
</Step>
<Step rID="T39">
<Obj plainTxt="False" ><![CDATA[Navigator]]></Obj>
<Details plainTxt="False" ><![CDATA[OracleFormWindow]]></Details>
<Time><![CDATA[12/23/2014 - 7:18:56]]></Time>
<TimeTick>1419299336</TimeTick>
<Step rID="T40">
<Obj plainTxt="False" ><![CDATA[Navigator.SelectMenu]]></Obj>
<Details plainTxt="False" ><![CDATA["View-&gtRequests"]]></Details>
<Time><![CDATA[12/23/2014 - 7:18:56]]></Time>
<TimeTick>1419299336</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="80" >
<Disp><![CDATA[Navigator.SelectMenu]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="11" nRep="79" >
<Disp><![CDATA[Navigator]]></Disp>
</NodeArgs>
</Step>
<Step rID="T41">
<Obj plainTxt="False" ><![CDATA[Find Requests]]></Obj>
<Details plainTxt="False" ><![CDATA[OracleFormWindow]]></Details>
<Time><![CDATA[12/23/2014 - 7:19:00]]></Time>
<TimeTick>1419299340</TimeTick>
<Step rID="T42">
<Obj plainTxt="False" ><![CDATA[Submit a New Request....Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[12/23/2014 - 7:19:00]]></Time>
<TimeTick>1419299340</TimeTick>
<NodeArgs eType="Replay" icon="13" nRep="83" >
<Disp><![CDATA[Submit a New Request....Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="11" nRep="82" >
<Disp><![CDATA[Find Requests]]></Disp>
</NodeArgs>
</Step>
<Step rID="T43">
<Obj plainTxt="False" ><![CDATA[Submit a New Request]]></Obj>
<Details plainTxt="False" ><![CDATA[OracleFormWindow]]></Details>
<Time><![CDATA[12/23/2014 - 7:19:02]]></Time>
<TimeTick>1419299342</TimeTick>
<Step rID="T44">
<Obj plainTxt="False" ><![CDATA[OK.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[12/23/2014 - 7:19:02]]></Time>
<TimeTick>1419299342</TimeTick>
<NodeArgs eType="Replay" icon="13" nRep="86" >
<Disp><![CDATA[OK.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="11" nRep="85" >
<Disp><![CDATA[Submit a New Request]]></Disp>
</NodeArgs>
</Step>
<Step rID="T45">
<Obj plainTxt="False" ><![CDATA[Submit Request]]></Obj>
<Details plainTxt="False" ><![CDATA[OracleFormWindow]]></Details>
<Time><![CDATA[12/23/2014 - 7:19:03]]></Time>
<TimeTick>1419299343</TimeTick>
<Step rID="T46">
<Obj plainTxt="False" ><![CDATA[Run this Request...|Name.Enter]]></Obj>
<Details plainTxt="False" ><![CDATA["Transfer Intercompany Transactions To General Ledger", True]]></Details>
<Time><![CDATA[12/23/2014 - 7:19:03]]></Time>
<TimeTick>1419299343</TimeTick>
<NodeArgs eType="Replay" icon="14" nRep="89" >
<Disp><![CDATA[Run this Request...|Name.Enter]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="11" nRep="88" >
<Disp><![CDATA[Submit Request]]></Disp>
</NodeArgs>
</Step>
<Step rID="T47">
<Obj plainTxt="False" ><![CDATA[Parameters]]></Obj>
<Details plainTxt="False" ><![CDATA[OracleFlexWindow]]></Details>
<Time><![CDATA[12/23/2014 - 7:19:07]]></Time>
<TimeTick>1419299347</TimeTick>
<Step rID="T48">
<Obj plainTxt="False" ><![CDATA[Ledger From.Enter]]></Obj>
<Details plainTxt="False" ><![CDATA["Rackspace - ILS Ledger", True]]></Details>
<Time><![CDATA[12/23/2014 - 7:19:07]]></Time>
<TimeTick>1419299347</TimeTick>
<NodeArgs eType="Replay" icon="14" nRep="92" >
<Disp><![CDATA[Ledger From.Enter]]></Disp>
</NodeArgs>
</Step>
<Step rID="T49">
<Obj plainTxt="False" ><![CDATA[Ledger To.Enter]]></Obj>
<Details plainTxt="False" ><![CDATA["Rackspace - ILS Ledger", True]]></Details>
<Time><![CDATA[12/23/2014 - 7:19:09]]></Time>
<TimeTick>1419299349</TimeTick>
<NodeArgs eType="Replay" icon="14" nRep="94" >
<Disp><![CDATA[Ledger To.Enter]]></Disp>
</NodeArgs>
</Step>
<Step rID="T50">
<Obj plainTxt="False" ><![CDATA[Run Journal Import.Enter]]></Obj>
<Details plainTxt="False" ><![CDATA["YES", True]]></Details>
<Time><![CDATA[12/23/2014 - 7:19:12]]></Time>
<TimeTick>1419299352</TimeTick>
<NodeArgs eType="Replay" icon="14" nRep="96" >
<Disp><![CDATA[Run Journal Import.Enter]]></Disp>
</NodeArgs>
</Step>
<Step rID="T51">
<Obj plainTxt="False" ><![CDATA[Parameters.Approve]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[12/23/2014 - 7:19:12]]></Time>
<TimeTick>1419299352</TimeTick>
<NodeArgs eType="Replay" icon="15" nRep="98" >
<Disp><![CDATA[Parameters.Approve]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="15" nRep="91" >
<Disp><![CDATA[Parameters]]></Disp>
</NodeArgs>
</Step>
<Step rID="T52">
<Obj plainTxt="False" ><![CDATA[Submit Request]]></Obj>
<Details plainTxt="False" ><![CDATA[OracleFormWindow]]></Details>
<Time><![CDATA[12/23/2014 - 7:19:18]]></Time>
<TimeTick>1419299358</TimeTick>
<Step rID="T53">
<Obj plainTxt="False" ><![CDATA[Submit.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[12/23/2014 - 7:19:18]]></Time>
<TimeTick>1419299358</TimeTick>
<NodeArgs eType="Replay" icon="13" nRep="101" >
<Disp><![CDATA[Submit.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="11" nRep="100" >
<Disp><![CDATA[Submit Request]]></Disp>
</NodeArgs>
</Step>
<Step rID="T54">
<Obj ><![CDATA[Validation Screenshot]]></Obj>
<Details ><![CDATA[Transfer Intercompany Transactions To GL  Parameters successfully Enter   ]]></Details>
<Time><![CDATA[12/23/2014 - 7:19:19]]></Time>
<TimeTick>1419299359</TimeTick>
<NodeArgs eType="User" icon="4" nRep="102" status="Information" >
<Disp><![CDATA[Validation Screenshot]]></Disp>
</NodeArgs>
</Step>
<Step rID="T55">
<Obj plainTxt="False" ><![CDATA[Find Requests]]></Obj>
<Details plainTxt="False" ><![CDATA[OracleFormWindow]]></Details>
<Time><![CDATA[12/23/2014 - 7:19:21]]></Time>
<TimeTick>1419299361</TimeTick>
<Step rID="T56">
<Obj plainTxt="False" ><![CDATA[Find Requests.CloseWindow]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[12/23/2014 - 7:19:21]]></Time>
<TimeTick>1419299361</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="105" >
<Disp><![CDATA[Find Requests.CloseWindow]]></Disp>
</NodeArgs>
</Step>
<Step rID="T57">
<Obj plainTxt="False" ><![CDATA[[ Decision ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[12/23/2014 - 7:19:22]]></Time>
<TimeTick>1419299362</TimeTick>
<NodeArgs eType="Replay" icon="16" nRep="106" >
<Disp><![CDATA[[ Decision ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T58">
<Obj plainTxt="False" ><![CDATA[[ Decision ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[12/23/2014 - 7:19:22]]></Time>
<TimeTick>1419299362</TimeTick>
<NodeArgs eType="Replay" icon="16" nRep="107" >
<Disp><![CDATA[[ Decision ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T59">
<Obj plainTxt="False" ><![CDATA[[ No ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[12/23/2014 - 7:19:22]]></Time>
<TimeTick>1419299362</TimeTick>
<NodeArgs eType="Replay" icon="13" nRep="108" >
<Disp><![CDATA[[ No ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T60">
<Obj plainTxt="False" ><![CDATA[[ No ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[12/23/2014 - 7:19:22]]></Time>
<TimeTick>1419299362</TimeTick>
<NodeArgs eType="Replay" icon="13" nRep="110" >
<Disp><![CDATA[[ No ].Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="11" nRep="104" >
<Disp><![CDATA[Find Requests]]></Disp>
</NodeArgs>
</Step>
<Step rID="T61">
<Obj plainTxt="False" ><![CDATA[Navigator]]></Obj>
<Details plainTxt="False" ><![CDATA[OracleFormWindow]]></Details>
<Time><![CDATA[12/23/2014 - 7:19:25]]></Time>
<TimeTick>1419299365</TimeTick>
<Step rID="T62">
<Obj plainTxt="False" ><![CDATA[Navigator.SelectMenu]]></Obj>
<Details plainTxt="False" ><![CDATA["View-&gtRequests"]]></Details>
<Time><![CDATA[12/23/2014 - 7:19:25]]></Time>
<TimeTick>1419299365</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="113" >
<Disp><![CDATA[Navigator.SelectMenu]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="11" nRep="112" >
<Disp><![CDATA[Navigator]]></Disp>
</NodeArgs>
</Step>
<Step rID="T63">
<Obj plainTxt="False" ><![CDATA[Find Requests]]></Obj>
<Details plainTxt="False" ><![CDATA[OracleFormWindow]]></Details>
<Time><![CDATA[12/23/2014 - 7:19:31]]></Time>
<TimeTick>1419299371</TimeTick>
<Step rID="T64">
<Obj plainTxt="False" ><![CDATA[My Completed Requests.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[12/23/2014 - 7:19:31]]></Time>
<TimeTick>1419299371</TimeTick>
<NodeArgs eType="Replay" icon="17" nRep="115" >
<Disp><![CDATA[My Completed Requests.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T65">
<Obj plainTxt="False" ><![CDATA[My Completed Requests.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["Specific Requests"]]></Details>
<Time><![CDATA[12/23/2014 - 7:19:32]]></Time>
<TimeTick>1419299372</TimeTick>
<NodeArgs eType="Replay" icon="17" nRep="117" >
<Disp><![CDATA[My Completed Requests.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T66">
<Obj plainTxt="False" ><![CDATA[Request ID.Enter]]></Obj>
<Details plainTxt="False" ><![CDATA["9782714", True]]></Details>
<Time><![CDATA[12/23/2014 - 7:19:32]]></Time>
<TimeTick>1419299372</TimeTick>
<NodeArgs eType="Replay" icon="14" nRep="119" >
<Disp><![CDATA[Request ID.Enter]]></Disp>
</NodeArgs>
</Step>
<Step rID="T67">
<Obj plainTxt="False" ><![CDATA[Find.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[12/23/2014 - 7:19:33]]></Time>
<TimeTick>1419299373</TimeTick>
<NodeArgs eType="Replay" icon="13" nRep="121" >
<Disp><![CDATA[Find.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="11" nRep="114" >
<Disp><![CDATA[Find Requests]]></Disp>
</NodeArgs>
</Step>
<Step rID="T68">
<Obj plainTxt="False" ><![CDATA[Requests]]></Obj>
<Details plainTxt="False" ><![CDATA[OracleFormWindow]]></Details>
<Time><![CDATA[12/23/2014 - 7:19:34]]></Time>
<TimeTick>1419299374</TimeTick>
<Step rID="T69">
<Obj plainTxt="False" ><![CDATA[Requests.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[12/23/2014 - 7:19:34]]></Time>
<TimeTick>1419299374</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="123" >
<Disp><![CDATA[Requests.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T70">
<Obj plainTxt="False" ><![CDATA[Table.GetFieldValue]]></Obj>
<Details plainTxt="False" ><![CDATA[1, "Phase"]]></Details>
<Time><![CDATA[12/23/2014 - 7:19:35]]></Time>
<TimeTick>1419299375</TimeTick>
<NodeArgs eType="Replay" icon="18" nRep="125" >
<Disp><![CDATA[Table.GetFieldValue]]></Disp>
</NodeArgs>
</Step>
<Step rID="T71">
<Obj plainTxt="False" ><![CDATA[Table.GetFieldValue]]></Obj>
<Details plainTxt="False" ><![CDATA[1, "Phase"]]></Details>
<Time><![CDATA[12/23/2014 - 7:19:35]]></Time>
<TimeTick>1419299375</TimeTick>
<NodeArgs eType="Replay" icon="18" nRep="127" >
<Disp><![CDATA[Table.GetFieldValue]]></Disp>
</NodeArgs>
</Step>
<Step rID="T72">
<Obj plainTxt="False" ><![CDATA[Table.GetFieldValue]]></Obj>
<Details plainTxt="False" ><![CDATA[1, "Phase"]]></Details>
<Time><![CDATA[12/23/2014 - 7:19:35]]></Time>
<TimeTick>1419299375</TimeTick>
<NodeArgs eType="Replay" icon="18" nRep="129" >
<Disp><![CDATA[Table.GetFieldValue]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="11" nRep="122" >
<Disp><![CDATA[Requests]]></Disp>
</NodeArgs>
</Step>
<Step rID="T73">
<Obj ><![CDATA[Request Phase]]></Obj>
<Details ><![CDATA[The Request Phase is correctly displayed as 'Completed'.]]></Details>
<Time><![CDATA[12/23/2014 - 7:19:35]]></Time>
<TimeTick>1419299375</TimeTick>
<NodeArgs eType="User" icon="4" nRep="130" status="Passed" >
<Disp><![CDATA[Request Phase]]></Disp>
</NodeArgs>
</Step>
<Step rID="T74">
<Obj ><![CDATA[Validation Screenshot]]></Obj>
<Details ><![CDATA[Validation Screenshot]]></Details>
<Time><![CDATA[12/23/2014 - 7:19:35]]></Time>
<TimeTick>1419299375</TimeTick>
<NodeArgs eType="User" icon="4" nRep="131" status="Information" >
<Disp><![CDATA[Validation Screenshot]]></Disp>
</NodeArgs>
</Step>
<Step rID="T75">
<Obj plainTxt="False" ><![CDATA[Requests]]></Obj>
<Details plainTxt="False" ><![CDATA[OracleFormWindow]]></Details>
<Time><![CDATA[12/23/2014 - 7:19:35]]></Time>
<TimeTick>1419299375</TimeTick>
<Step rID="T76">
<Obj plainTxt="False" ><![CDATA[Table.GetFieldValue]]></Obj>
<Details plainTxt="False" ><![CDATA[1, "Status"]]></Details>
<Time><![CDATA[12/23/2014 - 7:19:35]]></Time>
<TimeTick>1419299375</TimeTick>
<NodeArgs eType="Replay" icon="18" nRep="134" >
<Disp><![CDATA[Table.GetFieldValue]]></Disp>
</NodeArgs>
</Step>
<Step rID="T77">
<Obj plainTxt="False" ><![CDATA[Table.GetFieldValue]]></Obj>
<Details plainTxt="False" ><![CDATA[1, "Status"]]></Details>
<Time><![CDATA[12/23/2014 - 7:19:35]]></Time>
<TimeTick>1419299375</TimeTick>
<NodeArgs eType="Replay" icon="18" nRep="136" >
<Disp><![CDATA[Table.GetFieldValue]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="11" nRep="133" >
<Disp><![CDATA[Requests]]></Disp>
</NodeArgs>
</Step>
<Step rID="T78">
<Obj ><![CDATA[Request Status]]></Obj>
<Details ><![CDATA[The Request Status is correctly displayed as 'Normal'.]]></Details>
<Time><![CDATA[12/23/2014 - 7:19:35]]></Time>
<TimeTick>1419299375</TimeTick>
<NodeArgs eType="User" icon="4" nRep="137" status="Passed" >
<Disp><![CDATA[Request Status]]></Disp>
</NodeArgs>
</Step>
<Step rID="T79">
<Obj ><![CDATA[Validation Screenshot]]></Obj>
<Details ><![CDATA[Validation Screenshot]]></Details>
<Time><![CDATA[12/23/2014 - 7:19:35]]></Time>
<TimeTick>1419299375</TimeTick>
<NodeArgs eType="User" icon="4" nRep="138" status="Information" >
<Disp><![CDATA[Validation Screenshot]]></Disp>
</NodeArgs>
</Step>
<Step rID="T80">
<Obj ><![CDATA[End Component]]></Obj>
<Details ><![CDATA[Exiting Business component: Transfer_IT_To_GL]]></Details>
<Time><![CDATA[12/23/2014 - 7:19:35]]></Time>
<TimeTick>1419299375</TimeTick>
<NodeArgs eType="User" icon="4" nRep="139" >
<Disp><![CDATA[End Component]]></Disp>
</NodeArgs>
</Step>
<Step rID="T81">